apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy                      
    url: http://prometheus:9090        #the location of promethues instance
    isDefault: true
    uid: db69454e-e558-479e-b4fc-80db52bf91da
