
global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:
scrape_configs:
  - job_name: 'cadvisor'    #scrapes metrics from cadvisor
    scrape_interval: 1s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'
  - job_name: 'server_metrics'       #scrapes metrics from server
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server:8000']